version: '2'
services:
  app:
    build: .
    entrypoint: '/opt/app/bin/entrypoint.sh'
    volumes:
      - ./:/opt/app

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=app
      - POSTGRES_PASSWORD=password
    volumes:
      - data_postgres:/var/lib/postgresql/data

volumes:
  data_postgres: {}
